package com.admiral.themes

/**
 * AdmiralUI
 * Generated by Fastlane Figma Plugin.
 */

enum class ColorPaletteEnum {
    BACKGROUND_ACCENT,
    BACKGROUND_ACCENT_DARK,
    BACKGROUND_ACCENT_PRESSED,
    BACKGROUND_ADDITIONAL_ONE,
    BACKGROUND_ADDITIONAL_ONE_PRESSED,
    BACKGROUND_ADDITIONAL_TWO,
    BACKGROUND_ADDITIONAL_TWO_PRESSED,
    BACKGROUND_ATTENTION,
    BACKGROUND_ATTENTION_PRESSED,
    BACKGROUND_BASIC,
    BACKGROUND_ERROR,
    BACKGROUND_ERROR_PRESSED,
    BACKGROUND_EXTRA_SURFACE,
    BACKGROUND_MODAL_CONTROL,
    BACKGROUND_MODAL_VIEW,
    BACKGROUND_SECONDARY,
    BACKGROUND_SELECTED,
    BACKGROUND_SELECTED_PRESSED,
    BACKGROUND_SHADOW,
    BACKGROUND_SUCCESS,
    BACKGROUND_SUCCESS_PRESSED,
    ELEMENT_ACCENT,
    ELEMENT_ACCENT_ADDITIONAL,
    ELEMENT_ACCENT_PRESSED,
    ELEMENT_ADDITIONAL,
    ELEMENT_ATTENTION,
    ELEMENT_ATTENTION_DEFAULT,
    ELEMENT_ATTENTION_PRESSED,
    ELEMENT_BAR_DIVIDER,
    ELEMENT_CONTRAST,
    ELEMENT_ERROR,
    ELEMENT_ERROR_DEFAULT,
    ELEMENT_ERROR_PRESSED,
    ELEMENT_EXTRA,
    ELEMENT_PRIMARY,
    ELEMENT_SECONDARY,
    ELEMENT_STATIC_WHITE,
    ELEMENT_SUCCESS,
    ELEMENT_SUCCESS_DEFAULT,
    ELEMENT_SUCCESS_PRESSED,
    SPECIAL_EXTRA_01,
    SPECIAL_EXTRA_02,
    SPECIAL_EXTRA_03,
    SPECIAL_EXTRA_04,
    SPECIAL_EXTRA_05,
    SPECIAL_EXTRA_06,
    SPECIAL_EXTRA_07,
    SPECIAL_EXTRA_08,
    SPECIAL_EXTRA_09,
    SPECIAL_EXTRA_10,
    SPECIAL_EXTRA_11,
    SPECIAL_EXTRA_12,
    SPECIAL_EXTRA_13,
    SPECIAL_EXTRA_14,
    SPECIAL_EXTRA_15,
    SPECIAL_EXTRA_16,
    SPECIAL_EXTRA_17,
    SPECIAL_EXTRA_18,
    SPECIAL_EXTRA_19,
    SPECIAL_EXTRA_20,
    SPECIAL_EXTRA_21,
    SPECIAL_EXTRA_22,
    SPECIAL_EXTRA_23,
    SPECIAL_EXTRA_24,
    SPECIAL_EXTRA_25,
    SPECIAL_EXTRA_26,
    SPECIAL_EXTRA_27,
    TEXT_ACCENT,
    TEXT_ACCENT_ADDITIONAL,
    TEXT_ACCENT_PRESSED,
    TEXT_ADDITIONAL,
    TEXT_ATTENTION,
    TEXT_ATTENTION_DEFAULT,
    TEXT_ATTENTION_PRESSED,
    TEXT_CONTRAST,
    TEXT_ERROR,
    TEXT_ERROR_DEFAULT,
    TEXT_ERROR_PRESSED,
    TEXT_MASK,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    TEXT_STATIC_WHITE,
    TEXT_SUCCESS,
    TEXT_SUCCESS_DEFAULT,
    TEXT_SUCCESS_PRESSED,
    TRANSPARENT,
    STATIC_BLACK,
    BACKGROUND_ACCENT_TWO;

    companion object {
        fun from(index: Int?) = if (index == null) null else values()[index]

        @Suppress("LongMethod")
        fun ColorPaletteEnum?.colorResToToken(): Int? {
            return when (this) {
                BACKGROUND_ACCENT -> ThemeManager.theme.palette.backgroundAccent
                BACKGROUND_ACCENT_DARK -> ThemeManager.theme.palette.backgroundAccentDark
                BACKGROUND_ACCENT_PRESSED -> ThemeManager.theme.palette.backgroundAccentPressed
                BACKGROUND_ADDITIONAL_ONE -> ThemeManager.theme.palette.backgroundAdditionalOne
                BACKGROUND_ADDITIONAL_ONE_PRESSED -> ThemeManager.theme.palette.backgroundAdditionalOnePressed
                BACKGROUND_ADDITIONAL_TWO -> ThemeManager.theme.palette.backgroundAdditionalTwo
                BACKGROUND_ADDITIONAL_TWO_PRESSED -> ThemeManager.theme.palette.backgroundAdditionalTwoPressed
                BACKGROUND_ATTENTION -> ThemeManager.theme.palette.backgroundAttention
                BACKGROUND_ATTENTION_PRESSED -> ThemeManager.theme.palette.backgroundAttentionPressed
                BACKGROUND_BASIC -> ThemeManager.theme.palette.backgroundBasic
                BACKGROUND_ERROR -> ThemeManager.theme.palette.backgroundError
                BACKGROUND_ERROR_PRESSED -> ThemeManager.theme.palette.backgroundErrorPressed
                BACKGROUND_EXTRA_SURFACE -> ThemeManager.theme.palette.backgroundExtraSurface
                BACKGROUND_MODAL_CONTROL -> ThemeManager.theme.palette.backgroundModalControl
                BACKGROUND_MODAL_VIEW -> ThemeManager.theme.palette.backgroundModalView
                BACKGROUND_SECONDARY -> ThemeManager.theme.palette.backgroundSecondary
                BACKGROUND_SELECTED -> ThemeManager.theme.palette.backgroundSelected
                BACKGROUND_SELECTED_PRESSED -> ThemeManager.theme.palette.backgroundSelectedPressed
                BACKGROUND_SHADOW -> ThemeManager.theme.palette.backgroundShadow
                BACKGROUND_SUCCESS -> ThemeManager.theme.palette.backgroundSuccess
                BACKGROUND_SUCCESS_PRESSED -> ThemeManager.theme.palette.backgroundSuccessPressed
                ELEMENT_ACCENT -> ThemeManager.theme.palette.elementAccent
                ELEMENT_ACCENT_ADDITIONAL -> ThemeManager.theme.palette.elementAccentAdditional
                ELEMENT_ACCENT_PRESSED -> ThemeManager.theme.palette.elementAccentPressed
                ELEMENT_ADDITIONAL -> ThemeManager.theme.palette.elementAdditional
                ELEMENT_ATTENTION -> ThemeManager.theme.palette.elementAttention
                ELEMENT_ATTENTION_DEFAULT -> ThemeManager.theme.palette.elementAttentionDefault
                ELEMENT_ATTENTION_PRESSED -> ThemeManager.theme.palette.elementAttentionPressed
                ELEMENT_BAR_DIVIDER -> ThemeManager.theme.palette.elementBarDivider
                ELEMENT_CONTRAST -> ThemeManager.theme.palette.elementContrast
                ELEMENT_ERROR -> ThemeManager.theme.palette.elementError
                ELEMENT_ERROR_DEFAULT -> ThemeManager.theme.palette.elementErrorDefault
                ELEMENT_ERROR_PRESSED -> ThemeManager.theme.palette.elementErrorPressed
                ELEMENT_EXTRA -> ThemeManager.theme.palette.elementExtra
                ELEMENT_PRIMARY -> ThemeManager.theme.palette.elementPrimary
                ELEMENT_SECONDARY -> ThemeManager.theme.palette.elementSecondary
                ELEMENT_STATIC_WHITE -> ThemeManager.theme.palette.elementStaticWhite
                ELEMENT_SUCCESS -> ThemeManager.theme.palette.elementSuccess
                ELEMENT_SUCCESS_DEFAULT -> ThemeManager.theme.palette.elementSuccessDefault
                ELEMENT_SUCCESS_PRESSED -> ThemeManager.theme.palette.elementSuccessPressed
                SPECIAL_EXTRA_01 -> ThemeManager.theme.palette.specialExtra01
                SPECIAL_EXTRA_02 -> ThemeManager.theme.palette.specialExtra02
                SPECIAL_EXTRA_03 -> ThemeManager.theme.palette.specialExtra03
                SPECIAL_EXTRA_04 -> ThemeManager.theme.palette.specialExtra04
                SPECIAL_EXTRA_05 -> ThemeManager.theme.palette.specialExtra05
                SPECIAL_EXTRA_06 -> ThemeManager.theme.palette.specialExtra06
                SPECIAL_EXTRA_07 -> ThemeManager.theme.palette.specialExtra07
                SPECIAL_EXTRA_08 -> ThemeManager.theme.palette.specialExtra08
                SPECIAL_EXTRA_09 -> ThemeManager.theme.palette.specialExtra09
                SPECIAL_EXTRA_10 -> ThemeManager.theme.palette.specialExtra10
                SPECIAL_EXTRA_11 -> ThemeManager.theme.palette.specialExtra11
                SPECIAL_EXTRA_12 -> ThemeManager.theme.palette.specialExtra12
                SPECIAL_EXTRA_13 -> ThemeManager.theme.palette.specialExtra13
                SPECIAL_EXTRA_14 -> ThemeManager.theme.palette.specialExtra14
                SPECIAL_EXTRA_15 -> ThemeManager.theme.palette.specialExtra15
                SPECIAL_EXTRA_16 -> ThemeManager.theme.palette.specialExtra16
                SPECIAL_EXTRA_17 -> ThemeManager.theme.palette.specialExtra17
                SPECIAL_EXTRA_18 -> ThemeManager.theme.palette.specialExtra18
                SPECIAL_EXTRA_19 -> ThemeManager.theme.palette.specialExtra19
                SPECIAL_EXTRA_20 -> ThemeManager.theme.palette.specialExtra20
                SPECIAL_EXTRA_21 -> ThemeManager.theme.palette.specialExtra21
                SPECIAL_EXTRA_22 -> ThemeManager.theme.palette.specialExtra22
                SPECIAL_EXTRA_23 -> ThemeManager.theme.palette.specialExtra23
                SPECIAL_EXTRA_24 -> ThemeManager.theme.palette.specialExtra24
                SPECIAL_EXTRA_25 -> ThemeManager.theme.palette.specialExtra25
                SPECIAL_EXTRA_26 -> ThemeManager.theme.palette.specialExtra26
                SPECIAL_EXTRA_27 -> ThemeManager.theme.palette.specialExtra27
                TEXT_ACCENT -> ThemeManager.theme.palette.textAccent
                TEXT_ACCENT_ADDITIONAL -> ThemeManager.theme.palette.textAccentAdditional
                TEXT_ACCENT_PRESSED -> ThemeManager.theme.palette.textAccentPressed
                TEXT_ADDITIONAL -> ThemeManager.theme.palette.textAdditional
                TEXT_ATTENTION -> ThemeManager.theme.palette.textAttention
                TEXT_ATTENTION_DEFAULT -> ThemeManager.theme.palette.textAttentionDefault
                TEXT_ATTENTION_PRESSED -> ThemeManager.theme.palette.textAttentionPressed
                TEXT_CONTRAST -> ThemeManager.theme.palette.textContrast
                TEXT_ERROR -> ThemeManager.theme.palette.textError
                TEXT_ERROR_DEFAULT -> ThemeManager.theme.palette.textErrorDefault
                TEXT_ERROR_PRESSED -> ThemeManager.theme.palette.textErrorPressed
                TEXT_MASK -> ThemeManager.theme.palette.textMask
                TEXT_PRIMARY -> ThemeManager.theme.palette.textPrimary
                TEXT_SECONDARY -> ThemeManager.theme.palette.textSecondary
                TEXT_STATIC_WHITE -> ThemeManager.theme.palette.textStaticWhite
                TEXT_SUCCESS -> ThemeManager.theme.palette.textSuccess
                TEXT_SUCCESS_DEFAULT -> ThemeManager.theme.palette.textSuccessDefault
                TEXT_SUCCESS_PRESSED -> ThemeManager.theme.palette.textSuccessPressed
                TRANSPARENT -> ThemeManager.theme.palette.transparent
                STATIC_BLACK -> ThemeManager.theme.palette.staticBlack
                BACKGROUND_ACCENT_TWO -> ThemeManager.theme.palette.backgroundAccentTwo
                else -> null
            }
        }
    }
}