@file:Suppress("LongMethod")

package com.admiral.themes

import android.graphics.Color
import android.os.Parcelable
import androidx.annotation.ColorInt
import kotlinx.parcelize.Parcelize
import org.json.JSONObject

/**
 * AdmiralUI
 * Generated by Fastlane Figma Plugin.
 */

@Parcelize
@Suppress("LongParameterList")
open class ColorPalette(
    val name: String,
    val disabledAlpha: Double, 
    val backgroundAccent: Int,
    val backgroundAccentDark: Int,
    val backgroundAccentPressed: Int,
    val backgroundAdditionalOne: Int,
    val backgroundAdditionalOnePressed: Int,
    val backgroundAdditionalTwo: Int,
    val backgroundAdditionalTwoPressed: Int,
    val backgroundAttention: Int,
    val backgroundAttentionPressed: Int,
    val backgroundBasic: Int,
    val backgroundError: Int,
    val backgroundErrorPressed: Int,
    val backgroundExtraSurface: Int,
    val backgroundModalControl: Int,
    val backgroundModalView: Int,
    val backgroundSecondary: Int,
    val backgroundSelected: Int,
    val backgroundSelectedPressed: Int,
    val backgroundShadow: Int,
    val backgroundSuccess: Int,
    val backgroundSuccessPressed: Int,
    val elementAccent: Int,
    val elementAccentAdditional: Int,
    val elementAccentPressed: Int,
    val elementAdditional: Int,
    val elementAttention: Int,
    val elementAttentionDefault: Int,
    val elementAttentionPressed: Int,
    val elementBarDivider: Int,
    val elementContrast: Int,
    val elementError: Int,
    val elementErrorDefault: Int,
    val elementErrorPressed: Int,
    val elementExtra: Int,
    val elementPrimary: Int,
    val elementSecondary: Int,
    val elementStaticWhite: Int,
    val elementSuccess: Int,
    val elementSuccessDefault: Int,
    val elementSuccessPressed: Int,
    val specialExtra01: Int,
    val specialExtra02: Int,
    val specialExtra03: Int,
    val specialExtra04: Int,
    val specialExtra05: Int,
    val specialExtra06: Int,
    val specialExtra07: Int,
    val specialExtra08: Int,
    val specialExtra09: Int,
    val specialExtra10: Int,
    val specialExtra11: Int,
    val specialExtra12: Int,
    val specialExtra13: Int,
    val specialExtra14: Int,
    val specialExtra15: Int,
    val specialExtra16: Int,
    val specialExtra17: Int,
    val specialExtra18: Int,
    val specialExtra19: Int,
    val specialExtra20: Int,
    val specialExtra21: Int,
    val specialExtra22: Int,
    val specialExtra23: Int,
    val specialExtra24: Int,
    val specialExtra25: Int,
    val specialExtra26: Int,
    val specialExtra27: Int,
    val textAccent: Int,
    val textAccentAdditional: Int,
    val textAccentPressed: Int,
    val textAdditional: Int,
    val textAttention: Int,
    val textAttentionDefault: Int,
    val textAttentionPressed: Int,
    val textContrast: Int,
    val textError: Int,
    val textErrorDefault: Int,
    val textErrorPressed: Int,
    val textMask: Int,
    val textPrimary: Int,
    val textSecondary: Int,
    val textStaticWhite: Int,
    val textSuccess: Int,
    val textSuccessDefault: Int,
    val textSuccessPressed: Int,
) : Parcelable

internal fun ColorPalette.toJSON(): JSONObject {
    return JSONObject().apply {
        put("name", name)
        put("disabledAlpha", disabledAlpha)
        put("backgroundAccent", backgroundAccent)
        put("backgroundAccentDark", backgroundAccentDark)
        put("backgroundAccentPressed", backgroundAccentPressed)
        put("backgroundAdditionalOne", backgroundAdditionalOne)
        put("backgroundAdditionalOnePressed", backgroundAdditionalOnePressed)
        put("backgroundAdditionalTwo", backgroundAdditionalTwo)
        put("backgroundAdditionalTwoPressed", backgroundAdditionalTwoPressed)
        put("backgroundAttention", backgroundAttention)
        put("backgroundAttentionPressed", backgroundAttentionPressed)
        put("backgroundBasic", backgroundBasic)
        put("backgroundError", backgroundError)
        put("backgroundErrorPressed", backgroundErrorPressed)
        put("backgroundExtraSurface", backgroundExtraSurface)
        put("backgroundModalControl", backgroundModalControl)
        put("backgroundModalView", backgroundModalView)
        put("backgroundSecondary", backgroundSecondary)
        put("backgroundSelected", backgroundSelected)
        put("backgroundSelectedPressed", backgroundSelectedPressed)
        put("backgroundShadow", backgroundShadow)
        put("backgroundSuccess", backgroundSuccess)
        put("backgroundSuccessPressed", backgroundSuccessPressed)
        put("elementAccent", elementAccent)
        put("elementAccentAdditional", elementAccentAdditional)
        put("elementAccentPressed", elementAccentPressed)
        put("elementAdditional", elementAdditional)
        put("elementAttention", elementAttention)
        put("elementAttentionDefault", elementAttentionDefault)
        put("elementAttentionPressed", elementAttentionPressed)
        put("elementBarDivider", elementBarDivider)
        put("elementContrast", elementContrast)
        put("elementError", elementError)
        put("elementErrorDefault", elementErrorDefault)
        put("elementErrorPressed", elementErrorPressed)
        put("elementExtra", elementExtra)
        put("elementPrimary", elementPrimary)
        put("elementSecondary", elementSecondary)
        put("elementStaticWhite", elementStaticWhite)
        put("elementSuccess", elementSuccess)
        put("elementSuccessDefault", elementSuccessDefault)
        put("elementSuccessPressed", elementSuccessPressed)
        put("specialExtra01", specialExtra01)
        put("specialExtra02", specialExtra02)
        put("specialExtra03", specialExtra03)
        put("specialExtra04", specialExtra04)
        put("specialExtra05", specialExtra05)
        put("specialExtra06", specialExtra06)
        put("specialExtra07", specialExtra07)
        put("specialExtra08", specialExtra08)
        put("specialExtra09", specialExtra09)
        put("specialExtra10", specialExtra10)
        put("specialExtra11", specialExtra11)
        put("specialExtra12", specialExtra12)
        put("specialExtra13", specialExtra13)
        put("specialExtra14", specialExtra14)
        put("specialExtra15", specialExtra15)
        put("specialExtra16", specialExtra16)
        put("specialExtra17", specialExtra17)
        put("specialExtra18", specialExtra18)
        put("specialExtra19", specialExtra19)
        put("specialExtra20", specialExtra20)
        put("specialExtra21", specialExtra21)
        put("specialExtra22", specialExtra22)
        put("specialExtra23", specialExtra23)
        put("specialExtra24", specialExtra24)
        put("specialExtra25", specialExtra25)
        put("specialExtra26", specialExtra26)
        put("specialExtra27", specialExtra27)
        put("textAccent", textAccent)
        put("textAccentAdditional", textAccentAdditional)
        put("textAccentPressed", textAccentPressed)
        put("textAdditional", textAdditional)
        put("textAttention", textAttention)
        put("textAttentionDefault", textAttentionDefault)
        put("textAttentionPressed", textAttentionPressed)
        put("textContrast", textContrast)
        put("textError", textError)
        put("textErrorDefault", textErrorDefault)
        put("textErrorPressed", textErrorPressed)
        put("textMask", textMask)
        put("textPrimary", textPrimary)
        put("textSecondary", textSecondary)
        put("textStaticWhite", textStaticWhite)
        put("textSuccess", textSuccess)
        put("textSuccessDefault", textSuccessDefault)
        put("textSuccessPressed", textSuccessPressed)
    }
}

internal fun JSONObject.toPalette(): ColorPalette {
    return ColorPalette(
        name = getString("name"),
        disabledAlpha = getDouble("disabledAlpha"),
        backgroundAccent = getInt("backgroundAccent"),
        backgroundAccentDark = getInt("backgroundAccentDark"),
        backgroundAccentPressed = getInt("backgroundAccentPressed"),
        backgroundAdditionalOne = getInt("backgroundAdditionalOne"),
        backgroundAdditionalOnePressed = getInt("backgroundAdditionalOnePressed"),
        backgroundAdditionalTwo = getInt("backgroundAdditionalTwo"),
        backgroundAdditionalTwoPressed = getInt("backgroundAdditionalTwoPressed"),
        backgroundAttention = getInt("backgroundAttention"),
        backgroundAttentionPressed = getInt("backgroundAttentionPressed"),
        backgroundBasic = getInt("backgroundBasic"),
        backgroundError = getInt("backgroundError"),
        backgroundErrorPressed = getInt("backgroundErrorPressed"),
        backgroundExtraSurface = getInt("backgroundExtraSurface"),
        backgroundModalControl = getInt("backgroundModalControl"),
        backgroundModalView = getInt("backgroundModalView"),
        backgroundSecondary = getInt("backgroundSecondary"),
        backgroundSelected = getInt("backgroundSelected"),
        backgroundSelectedPressed = getInt("backgroundSelectedPressed"),
        backgroundShadow = getInt("backgroundShadow"),
        backgroundSuccess = getInt("backgroundSuccess"),
        backgroundSuccessPressed = getInt("backgroundSuccessPressed"),
        elementAccent = getInt("elementAccent"),
        elementAccentAdditional = getInt("elementAccentAdditional"),
        elementAccentPressed = getInt("elementAccentPressed"),
        elementAdditional = getInt("elementAdditional"),
        elementAttention = getInt("elementAttention"),
        elementAttentionDefault = getInt("elementAttentionDefault"),
        elementAttentionPressed = getInt("elementAttentionPressed"),
        elementBarDivider = getInt("elementBarDivider"),
        elementContrast = getInt("elementContrast"),
        elementError = getInt("elementError"),
        elementErrorDefault = getInt("elementErrorDefault"),
        elementErrorPressed = getInt("elementErrorPressed"),
        elementExtra = getInt("elementExtra"),
        elementPrimary = getInt("elementPrimary"),
        elementSecondary = getInt("elementSecondary"),
        elementStaticWhite = getInt("elementStaticWhite"),
        elementSuccess = getInt("elementSuccess"),
        elementSuccessDefault = getInt("elementSuccessDefault"),
        elementSuccessPressed = getInt("elementSuccessPressed"),
        specialExtra01 = getInt("specialExtra01"),
        specialExtra02 = getInt("specialExtra02"),
        specialExtra03 = getInt("specialExtra03"),
        specialExtra04 = getInt("specialExtra04"),
        specialExtra05 = getInt("specialExtra05"),
        specialExtra06 = getInt("specialExtra06"),
        specialExtra07 = getInt("specialExtra07"),
        specialExtra08 = getInt("specialExtra08"),
        specialExtra09 = getInt("specialExtra09"),
        specialExtra10 = getInt("specialExtra10"),
        specialExtra11 = getInt("specialExtra11"),
        specialExtra12 = getInt("specialExtra12"),
        specialExtra13 = getInt("specialExtra13"),
        specialExtra14 = getInt("specialExtra14"),
        specialExtra15 = getInt("specialExtra15"),
        specialExtra16 = getInt("specialExtra16"),
        specialExtra17 = getInt("specialExtra17"),
        specialExtra18 = getInt("specialExtra18"),
        specialExtra19 = getInt("specialExtra19"),
        specialExtra20 = getInt("specialExtra20"),
        specialExtra21 = getInt("specialExtra21"),
        specialExtra22 = getInt("specialExtra22"),
        specialExtra23 = getInt("specialExtra23"),
        specialExtra24 = getInt("specialExtra24"),
        specialExtra25 = getInt("specialExtra25"),
        specialExtra26 = getInt("specialExtra26"),
        specialExtra27 = getInt("specialExtra27"),
        textAccent = getInt("textAccent"),
        textAccentAdditional = getInt("textAccentAdditional"),
        textAccentPressed = getInt("textAccentPressed"),
        textAdditional = getInt("textAdditional"),
        textAttention = getInt("textAttention"),
        textAttentionDefault = getInt("textAttentionDefault"),
        textAttentionPressed = getInt("textAttentionPressed"),
        textContrast = getInt("textContrast"),
        textError = getInt("textError"),
        textErrorDefault = getInt("textErrorDefault"),
        textErrorPressed = getInt("textErrorPressed"),
        textMask = getInt("textMask"),
        textPrimary = getInt("textPrimary"),
        textSecondary = getInt("textSecondary"),
        textStaticWhite = getInt("textStaticWhite"),
        textSuccess = getInt("textSuccess"),
        textSuccessDefault = getInt("textSuccessDefault"),
        textSuccessPressed = getInt("textSuccessPressed"),
    )
}

internal fun darkPalette() = ColorPalette(
    name = THEME_DARK,
    disabledAlpha = 0.6,
    backgroundAccent = Color.parseColor("#FF3A83F1"),
    backgroundAccentDark = Color.parseColor("#FF373B49"),
    backgroundAccentPressed = Color.parseColor("#FF326DC6"),
    backgroundAdditionalOne = Color.parseColor("#FF23262F"),
    backgroundAdditionalOnePressed = Color.parseColor("#FF1A1C24"),
    backgroundAdditionalTwo = Color.parseColor("#FF373B49"),
    backgroundAdditionalTwoPressed = Color.parseColor("#FF23262F"),
    backgroundAttention = Color.parseColor("#FF382C25"),
    backgroundAttentionPressed = Color.parseColor("#FF252020"),
    backgroundBasic = Color.parseColor("#FF13151B"),
    backgroundError = Color.parseColor("#FF3D1F22"),
    backgroundErrorPressed = Color.parseColor("#FF281A1E"),
    backgroundExtraSurface = Color.parseColor("#FF373B49"),
    backgroundModalControl = Color.parseColor("#7F13151B"),
    backgroundModalView = Color.parseColor("#CC31353F"),
    backgroundSecondary = Color.parseColor("#FF585E6A"),
    backgroundSelected = Color.parseColor("#FF1B2B46"),
    backgroundSelectedPressed = Color.parseColor("#FF172030"),
    backgroundShadow = Color.parseColor("#00000000"),
    backgroundSuccess = Color.parseColor("#FF1B302A"),
    backgroundSuccessPressed = Color.parseColor("#FF172322"),
    elementAccent = Color.parseColor("#FF3A83F1"),
    elementAccentAdditional = Color.parseColor("#FFA0C0EF"),
    elementAccentPressed = Color.parseColor("#FF326DC6"),
    elementAdditional = Color.parseColor("#FF373B49"),
    elementAttention = Color.parseColor("#FFCB884C"),
    elementAttentionDefault = Color.parseColor("#FFBD997C"),
    elementAttentionPressed = Color.parseColor("#FFA67142"),
    elementBarDivider = Color.parseColor("#00000000"),
    elementContrast = Color.parseColor("#FFFFFFFF"),
    elementError = Color.parseColor("#FFE7463E"),
    elementErrorDefault = Color.parseColor("#FFCC827F"),
    elementErrorPressed = Color.parseColor("#FF88302F"),
    elementExtra = Color.parseColor("#FFFFFFFF"),
    elementPrimary = Color.parseColor("#FF787E8D"),
    elementSecondary = Color.parseColor("#FF585E6A"),
    elementStaticWhite = Color.parseColor("#FFFFFFFF"),
    elementSuccess = Color.parseColor("#FF3B9D65"),
    elementSuccessDefault = Color.parseColor("#FF89B79D"),
    elementSuccessPressed = Color.parseColor("#FF338256"),
    specialExtra01 = Color.parseColor("#FFED6CCD"),
    specialExtra02 = Color.parseColor("#FFC368DA"),
    specialExtra03 = Color.parseColor("#FF9963F6"),
    specialExtra04 = Color.parseColor("#FFF86C85"),
    specialExtra05 = Color.parseColor("#FFD8477B"),
    specialExtra06 = Color.parseColor("#FFF0DD37"),
    specialExtra07 = Color.parseColor("#FFFFAF37"),
    specialExtra08 = Color.parseColor("#FFFF8515"),
    specialExtra09 = Color.parseColor("#FFFF5931"),
    specialExtra10 = Color.parseColor("#FFC0D20F"),
    specialExtra11 = Color.parseColor("#FF5ECF70"),
    specialExtra12 = Color.parseColor("#FF5BD8D1"),
    specialExtra13 = Color.parseColor("#FF24A79F"),
    specialExtra14 = Color.parseColor("#FF147F94"),
    specialExtra15 = Color.parseColor("#FF00BCD4"),
    specialExtra16 = Color.parseColor("#FF0ABBFB"),
    specialExtra17 = Color.parseColor("#FF3F7CFD"),
    specialExtra18 = Color.parseColor("#FF3E51B5"),
    specialExtra19 = Color.parseColor("#FF23262F"),
    specialExtra20 = Color.parseColor("#FF23262F"),
    specialExtra21 = Color.parseColor("#FF23262F"),
    specialExtra22 = Color.parseColor("#FF23262F"),
    specialExtra23 = Color.parseColor("#FF23262F"),
    specialExtra24 = Color.parseColor("#FF23262F"),
    specialExtra25 = Color.parseColor("#FF23262F"),
    specialExtra26 = Color.parseColor("#FF23262F"),
    specialExtra27 = Color.parseColor("#FF23262F"),
    textAccent = Color.parseColor("#FF3A83F1"),
    textAccentAdditional = Color.parseColor("#FFA0C0EF"),
    textAccentPressed = Color.parseColor("#FF326DC6"),
    textAdditional = Color.parseColor("#FF99A1B1"),
    textAttention = Color.parseColor("#FFCB884C"),
    textAttentionDefault = Color.parseColor("#FFBD997C"),
    textAttentionPressed = Color.parseColor("#FFA67142"),
    textContrast = Color.parseColor("#FFFFFFFF"),
    textError = Color.parseColor("#FFE7463E"),
    textErrorDefault = Color.parseColor("#FFCC827F"),
    textErrorPressed = Color.parseColor("#FF88302F"),
    textMask = Color.parseColor("#FF585E6A"),
    textPrimary = Color.parseColor("#FFE3E8F0"),
    textSecondary = Color.parseColor("#FF787E8D"),
    textStaticWhite = Color.parseColor("#FFFFFFFF"),
    textSuccess = Color.parseColor("#FF3B9D65"),
    textSuccessDefault = Color.parseColor("#FF89B79D"),
    textSuccessPressed = Color.parseColor("#FF338256")
)

internal fun lightPalette() = ColorPalette(
    name = THEME_LIGHT,
    disabledAlpha = 0.6,
    backgroundAccent = Color.parseColor("#FF3A83F1"),
    backgroundAccentDark = Color.parseColor("#FF0B1D37"),
    backgroundAccentPressed = Color.parseColor("#FF316FCC"),
    backgroundAdditionalOne = Color.parseColor("#FFF3F4F7"),
    backgroundAdditionalOnePressed = Color.parseColor("#FFE4E8EE"),
    backgroundAdditionalTwo = Color.parseColor("#FFE4E8EE"),
    backgroundAdditionalTwoPressed = Color.parseColor("#FFD5D8DF"),
    backgroundAttention = Color.parseColor("#FFFFEFD7"),
    backgroundAttentionPressed = Color.parseColor("#FFFFDFAF"),
    backgroundBasic = Color.parseColor("#FFFFFFFF"),
    backgroundError = Color.parseColor("#FFFFEBEA"),
    backgroundErrorPressed = Color.parseColor("#FFFFD8D6"),
    backgroundExtraSurface = Color.parseColor("#FFFFFFFF"),
    backgroundModalControl = Color.parseColor("#7FFFFFFF"),
    backgroundModalView = Color.parseColor("#6621242C"),
    backgroundSecondary = Color.parseColor("#FF515764"),
    backgroundSelected = Color.parseColor("#FFEBF3FE"),
    backgroundSelectedPressed = Color.parseColor("#FFD8E6FC"),
    backgroundShadow = Color.parseColor("#4C353843"),
    backgroundSuccess = Color.parseColor("#FFECF9F1"),
    backgroundSuccessPressed = Color.parseColor("#FFDAF2E4"),
    elementAccent = Color.parseColor("#FF3A83F1"),
    elementAccentAdditional = Color.parseColor("#FFB0CDF9"),
    elementAccentPressed = Color.parseColor("#FF316FCC"),
    elementAdditional = Color.parseColor("#FFE4E8EE"),
    elementAttention = Color.parseColor("#FFFA9130"),
    elementAttentionDefault = Color.parseColor("#FFDEA370"),
    elementAttentionPressed = Color.parseColor("#FFC26B22"),
    elementBarDivider = Color.parseColor("#00FFFFFF"),
    elementContrast = Color.parseColor("#FFFFFFFF"),
    elementError = Color.parseColor("#FFFF3B30"),
    elementErrorDefault = Color.parseColor("#FFE58785"),
    elementErrorPressed = Color.parseColor("#FFD62F26"),
    elementExtra = Color.parseColor("#FF999EA9"),
    elementPrimary = Color.parseColor("#FF999EA9"),
    elementSecondary = Color.parseColor("#FF515764"),
    elementStaticWhite = Color.parseColor("#FFFFFFFF"),
    elementSuccess = Color.parseColor("#FF44BF78"),
    elementSuccessDefault = Color.parseColor("#FF84D0A7"),
    elementSuccessPressed = Color.parseColor("#FF33985D"),
    specialExtra01 = Color.parseColor("#FFED6CCD"),
    specialExtra02 = Color.parseColor("#FFC368DA"),
    specialExtra03 = Color.parseColor("#FF9963F6"),
    specialExtra04 = Color.parseColor("#FFF86C85"),
    specialExtra05 = Color.parseColor("#FFD8477B"),
    specialExtra06 = Color.parseColor("#FFF0DD37"),
    specialExtra07 = Color.parseColor("#FFFFAF37"),
    specialExtra08 = Color.parseColor("#FFFF8515"),
    specialExtra09 = Color.parseColor("#FFFF5931"),
    specialExtra10 = Color.parseColor("#FFC0D20F"),
    specialExtra11 = Color.parseColor("#FF5ECF70"),
    specialExtra12 = Color.parseColor("#FF5BD8D1"),
    specialExtra13 = Color.parseColor("#FF24A79F"),
    specialExtra14 = Color.parseColor("#FF147F94"),
    specialExtra15 = Color.parseColor("#FF00BCD4"),
    specialExtra16 = Color.parseColor("#FF0ABBFB"),
    specialExtra17 = Color.parseColor("#FF3F7CFD"),
    specialExtra18 = Color.parseColor("#FF3E51B5"),
    specialExtra19 = Color.parseColor("#FFE0F2FF"),
    specialExtra20 = Color.parseColor("#FFE2F4FD"),
    specialExtra21 = Color.parseColor("#FFDBF8FF"),
    specialExtra22 = Color.parseColor("#FFD8F5E8"),
    specialExtra23 = Color.parseColor("#FFECF0FF"),
    specialExtra24 = Color.parseColor("#FFFFEBF8"),
    specialExtra25 = Color.parseColor("#FFFFEBED"),
    specialExtra26 = Color.parseColor("#FFF9EECF"),
    specialExtra27 = Color.parseColor("#FFFFF1D4"),
    textAccent = Color.parseColor("#FF3A83F1"),
    textAccentAdditional = Color.parseColor("#FFB0CDF9"),
    textAccentPressed = Color.parseColor("#FF316FCC"),
    textAdditional = Color.parseColor("#FF515764"),
    textAttention = Color.parseColor("#FFFA9130"),
    textAttentionDefault = Color.parseColor("#FFDEA370"),
    textAttentionPressed = Color.parseColor("#FFC26B22"),
    textContrast = Color.parseColor("#FFFFFFFF"),
    textError = Color.parseColor("#FFFF3B30"),
    textErrorDefault = Color.parseColor("#FFE58785"),
    textErrorPressed = Color.parseColor("#FFD62F26"),
    textMask = Color.parseColor("#FFD5D8DF"),
    textPrimary = Color.parseColor("#FF21242C"),
    textSecondary = Color.parseColor("#FF999EA9"),
    textStaticWhite = Color.parseColor("#FFFFFFFF"),
    textSuccess = Color.parseColor("#FF44BF78"),
    textSuccessDefault = Color.parseColor("#FF84D0A7"),
    textSuccessPressed = Color.parseColor("#FF33985D")
)

internal fun sMEDarkPalette() = ColorPalette(
    name = THEME_DARK,
    disabledAlpha = 0.6,
    backgroundAccent = Color.parseColor("#FF189FE2"),
    backgroundAccentDark = Color.parseColor("#FF3F4553"),
    backgroundAccentPressed = Color.parseColor("#FF137CB0"),
    backgroundAdditionalOne = Color.parseColor("#FF303643"),
    backgroundAdditionalOnePressed = Color.parseColor("#FF3F4553"),
    backgroundAdditionalTwo = Color.parseColor("#FF3F4553"),
    backgroundAdditionalTwoPressed = Color.parseColor("#FF4E5566"),
    backgroundAttention = Color.parseColor("#FF493A1C"),
    backgroundAttentionPressed = Color.parseColor("#FF3A2E16"),
    backgroundBasic = Color.parseColor("#FF000000"),
    backgroundError = Color.parseColor("#FF361C22"),
    backgroundErrorPressed = Color.parseColor("#FF2B161B"),
    backgroundExtraSurface = Color.parseColor("#FF3F4553"),
    backgroundModalControl = Color.parseColor("#7F13151B"),
    backgroundModalView = Color.parseColor("#CC23252E"),
    backgroundSecondary = Color.parseColor("#FF8C92A3"),
    backgroundSelected = Color.parseColor("#FF15313F"),
    backgroundSelectedPressed = Color.parseColor("#FF0F222D"),
    backgroundShadow = Color.parseColor("#00000000"),
    backgroundSuccess = Color.parseColor("#FF0C3629"),
    backgroundSuccessPressed = Color.parseColor("#FF0A2B21"),
    elementAccent = Color.parseColor("#FF33BBFF"),
    elementAccentAdditional = Color.parseColor("#FF0F222D"),
    elementAccentPressed = Color.parseColor("#FF2996CC"),
    elementAdditional = Color.parseColor("#FF3F4553"),
    elementAttention = Color.parseColor("#FFE39C38"),
    elementAttentionDefault = Color.parseColor("#FFD0B288"),
    elementAttentionPressed = Color.parseColor("#FFB67D2D"),
    elementBarDivider = Color.parseColor("#00000000"),
    elementContrast = Color.parseColor("#FFC6CAD8"),
    elementError = Color.parseColor("#FFFF4667"),
    elementErrorDefault = Color.parseColor("#FFEA94A3"),
    elementErrorPressed = Color.parseColor("#FFCC3852"),
    elementExtra = Color.parseColor("#FFE8EAF1"),
    elementPrimary = Color.parseColor("#FF8C92A3"),
    elementSecondary = Color.parseColor("#FF5C6477"),
    elementStaticWhite = Color.parseColor("#FFFFFFFF"),
    elementSuccess = Color.parseColor("#FF32C196"),
    elementSuccessDefault = Color.parseColor("#FF90D0BC"),
    elementSuccessPressed = Color.parseColor("#FF299B78"),
    specialExtra01 = Color.parseColor("#FFED6CCD"),
    specialExtra02 = Color.parseColor("#FFC368DA"),
    specialExtra03 = Color.parseColor("#FF9963F6"),
    specialExtra04 = Color.parseColor("#FFF86C85"),
    specialExtra05 = Color.parseColor("#FFD8477B"),
    specialExtra06 = Color.parseColor("#FFF0DD37"),
    specialExtra07 = Color.parseColor("#FFFFAF37"),
    specialExtra08 = Color.parseColor("#FFFF8515"),
    specialExtra09 = Color.parseColor("#FFFF5931"),
    specialExtra10 = Color.parseColor("#FFC0D20F"),
    specialExtra11 = Color.parseColor("#FF5ECF70"),
    specialExtra12 = Color.parseColor("#FF5BD8D1"),
    specialExtra13 = Color.parseColor("#FF24A79F"),
    specialExtra14 = Color.parseColor("#FF147F94"),
    specialExtra15 = Color.parseColor("#FF00BCD4"),
    specialExtra16 = Color.parseColor("#FF0ABBFB"),
    specialExtra17 = Color.parseColor("#FF3F7CFD"),
    specialExtra18 = Color.parseColor("#FF3E51B5"),
    specialExtra19 = Color.parseColor("#FF23262F"),
    specialExtra20 = Color.parseColor("#FF23262F"),
    specialExtra21 = Color.parseColor("#FF23262F"),
    specialExtra22 = Color.parseColor("#FF23262F"),
    specialExtra23 = Color.parseColor("#FF23262F"),
    specialExtra24 = Color.parseColor("#FF23262F"),
    specialExtra25 = Color.parseColor("#FF23262F"),
    specialExtra26 = Color.parseColor("#FF23262F"),
    specialExtra27 = Color.parseColor("#FF23262F"),
    textAccent = Color.parseColor("#FF33BBFF"),
    textAccentAdditional = Color.parseColor("#FF0F222D"),
    textAccentPressed = Color.parseColor("#FF189FE2"),
    textAdditional = Color.parseColor("#FFBABDCA"),
    textAttention = Color.parseColor("#FFE39C38"),
    textAttentionDefault = Color.parseColor("#FFD0B288"),
    textAttentionPressed = Color.parseColor("#FFB67D2D"),
    textContrast = Color.parseColor("#FFC6CAD8"),
    textError = Color.parseColor("#FFFF4667"),
    textErrorDefault = Color.parseColor("#FFEA94A3"),
    textErrorPressed = Color.parseColor("#FFCC3852"),
    textMask = Color.parseColor("#FF7A7F8D"),
    textPrimary = Color.parseColor("#FFFFFFFF"),
    textSecondary = Color.parseColor("#FF8C92A3"),
    textStaticWhite = Color.parseColor("#FFFFFFFF"),
    textSuccess = Color.parseColor("#FF32C196"),
    textSuccessDefault = Color.parseColor("#FF90D0BC"),
    textSuccessPressed = Color.parseColor("#FF299B78")
)

internal fun sMELightPalette() = ColorPalette(
    name = THEME_LIGHT,
    disabledAlpha = 0.6,
    backgroundAccent = Color.parseColor("#FF00AAFF"),
    backgroundAccentDark = Color.parseColor("#FFFFFFFF"),
    backgroundAccentPressed = Color.parseColor("#FF0099E5"),
    backgroundAdditionalOne = Color.parseColor("#FFF1F1F6"),
    backgroundAdditionalOnePressed = Color.parseColor("#FFE8EAF1"),
    backgroundAdditionalTwo = Color.parseColor("#FFE8EAF1"),
    backgroundAdditionalTwoPressed = Color.parseColor("#FFDDDFE8"),
    backgroundAttention = Color.parseColor("#FFFFF8DD"),
    backgroundAttentionPressed = Color.parseColor("#FFFFF1CC"),
    backgroundBasic = Color.parseColor("#FFFFFFFF"),
    backgroundError = Color.parseColor("#FFFFECF0"),
    backgroundErrorPressed = Color.parseColor("#FFFFDAE1"),
    backgroundExtraSurface = Color.parseColor("#FFFFFFFF"),
    backgroundModalControl = Color.parseColor("#7FFFFFFF"),
    backgroundModalView = Color.parseColor("#66000000"),
    backgroundSecondary = Color.parseColor("#FF5A606F"),
    backgroundSelected = Color.parseColor("#FFEBF8FF"),
    backgroundSelectedPressed = Color.parseColor("#FFD9F2FF"),
    backgroundShadow = Color.parseColor("#4C353843"),
    backgroundSuccess = Color.parseColor("#FFE9F8F4"),
    backgroundSuccessPressed = Color.parseColor("#FFD3F1E8"),
    elementAccent = Color.parseColor("#FF00AAFF"),
    elementAccentAdditional = Color.parseColor("#FFD9F2FF"),
    elementAccentPressed = Color.parseColor("#FF0088CC"),
    elementAdditional = Color.parseColor("#FFE8EAF1"),
    elementAttention = Color.parseColor("#FFFF9500"),
    elementAttentionDefault = Color.parseColor("#FFDCB279"),
    elementAttentionPressed = Color.parseColor("#FFCC7700"),
    elementBarDivider = Color.parseColor("#FFE8EAF1"),
    elementContrast = Color.parseColor("#FF8C92A3"),
    elementError = Color.parseColor("#FFFF4667"),
    elementErrorDefault = Color.parseColor("#FFD27586"),
    elementErrorPressed = Color.parseColor("#FFCC3852"),
    elementExtra = Color.parseColor("#FF8C92A3"),
    elementPrimary = Color.parseColor("#FF8C92A3"),
    elementSecondary = Color.parseColor("#FF000614"),
    elementStaticWhite = Color.parseColor("#FFFFFFFF"),
    elementSuccess = Color.parseColor("#FF00A976"),
    elementSuccessDefault = Color.parseColor("#FF7FAFA0"),
    elementSuccessPressed = Color.parseColor("#FF00875E"),
    specialExtra01 = Color.parseColor("#FFED6CCD"),
    specialExtra02 = Color.parseColor("#FFC368DA"),
    specialExtra03 = Color.parseColor("#FF9963F6"),
    specialExtra04 = Color.parseColor("#FFF86C85"),
    specialExtra05 = Color.parseColor("#FFD8477B"),
    specialExtra06 = Color.parseColor("#FFF0DD37"),
    specialExtra07 = Color.parseColor("#FFFFAF37"),
    specialExtra08 = Color.parseColor("#FFFF8515"),
    specialExtra09 = Color.parseColor("#FFFF5931"),
    specialExtra10 = Color.parseColor("#FFC0D20F"),
    specialExtra11 = Color.parseColor("#FF5ECF70"),
    specialExtra12 = Color.parseColor("#FF5BD8D1"),
    specialExtra13 = Color.parseColor("#FF24A79F"),
    specialExtra14 = Color.parseColor("#FF147F94"),
    specialExtra15 = Color.parseColor("#FF00BCD4"),
    specialExtra16 = Color.parseColor("#FF0ABBFB"),
    specialExtra17 = Color.parseColor("#FF3F7CFD"),
    specialExtra18 = Color.parseColor("#FF3E51B5"),
    specialExtra19 = Color.parseColor("#FFE0F2FF"),
    specialExtra20 = Color.parseColor("#FFE2F4FD"),
    specialExtra21 = Color.parseColor("#FFDBF8FF"),
    specialExtra22 = Color.parseColor("#FFD8F5E8"),
    specialExtra23 = Color.parseColor("#FFECF0FF"),
    specialExtra24 = Color.parseColor("#FFFFEBF8"),
    specialExtra25 = Color.parseColor("#FFFFEBED"),
    specialExtra26 = Color.parseColor("#FFF9EECF"),
    specialExtra27 = Color.parseColor("#FFFFF1D4"),
    textAccent = Color.parseColor("#FF0099E5"),
    textAccentAdditional = Color.parseColor("#FFD9F2FF"),
    textAccentPressed = Color.parseColor("#FF00AAFF"),
    textAdditional = Color.parseColor("#FF5A606F"),
    textAttention = Color.parseColor("#FFFF9500"),
    textAttentionDefault = Color.parseColor("#FFDCB279"),
    textAttentionPressed = Color.parseColor("#FFCC7700"),
    textContrast = Color.parseColor("#FF8C92A3"),
    textError = Color.parseColor("#FFFF4667"),
    textErrorDefault = Color.parseColor("#FFD27586"),
    textErrorPressed = Color.parseColor("#FFCC3852"),
    textMask = Color.parseColor("#FFBABDCA"),
    textPrimary = Color.parseColor("#FF000614"),
    textSecondary = Color.parseColor("#FF8C92A3"),
    textStaticWhite = Color.parseColor("#FFFFFFFF"),
    textSuccess = Color.parseColor("#FF00A976"),
    textSuccessDefault = Color.parseColor("#FF7FAFA0"),
    textSuccessPressed = Color.parseColor("#FF00875E")
)

fun ColorPalette.changeColor(colorName: String, @ColorInt color: Int): ColorPalette {
    return when (colorName) { 
        "backgroundAccent" -> copy(backgroundAccent = color)
        "backgroundAccentDark" -> copy(backgroundAccentDark = color)
        "backgroundAccentPressed" -> copy(backgroundAccentPressed = color)
        "backgroundAdditionalOne" -> copy(backgroundAdditionalOne = color)
        "backgroundAdditionalOnePressed" -> copy(backgroundAdditionalOnePressed = color)
        "backgroundAdditionalTwo" -> copy(backgroundAdditionalTwo = color)
        "backgroundAdditionalTwoPressed" -> copy(backgroundAdditionalTwoPressed = color)
        "backgroundAttention" -> copy(backgroundAttention = color)
        "backgroundAttentionPressed" -> copy(backgroundAttentionPressed = color)
        "backgroundBasic" -> copy(backgroundBasic = color)
        "backgroundError" -> copy(backgroundError = color)
        "backgroundErrorPressed" -> copy(backgroundErrorPressed = color)
        "backgroundExtraSurface" -> copy(backgroundExtraSurface = color)
        "backgroundModalControl" -> copy(backgroundModalControl = color)
        "backgroundModalView" -> copy(backgroundModalView = color)
        "backgroundSecondary" -> copy(backgroundSecondary = color)
        "backgroundSelected" -> copy(backgroundSelected = color)
        "backgroundSelectedPressed" -> copy(backgroundSelectedPressed = color)
        "backgroundShadow" -> copy(backgroundShadow = color)
        "backgroundSuccess" -> copy(backgroundSuccess = color)
        "backgroundSuccessPressed" -> copy(backgroundSuccessPressed = color)
        "elementAccent" -> copy(elementAccent = color)
        "elementAccentAdditional" -> copy(elementAccentAdditional = color)
        "elementAccentPressed" -> copy(elementAccentPressed = color)
        "elementAdditional" -> copy(elementAdditional = color)
        "elementAttention" -> copy(elementAttention = color)
        "elementAttentionDefault" -> copy(elementAttentionDefault = color)
        "elementAttentionPressed" -> copy(elementAttentionPressed = color)
        "elementBarDivider" -> copy(elementBarDivider = color)
        "elementContrast" -> copy(elementContrast = color)
        "elementError" -> copy(elementError = color)
        "elementErrorDefault" -> copy(elementErrorDefault = color)
        "elementErrorPressed" -> copy(elementErrorPressed = color)
        "elementExtra" -> copy(elementExtra = color)
        "elementPrimary" -> copy(elementPrimary = color)
        "elementSecondary" -> copy(elementSecondary = color)
        "elementStaticWhite" -> copy(elementStaticWhite = color)
        "elementSuccess" -> copy(elementSuccess = color)
        "elementSuccessDefault" -> copy(elementSuccessDefault = color)
        "elementSuccessPressed" -> copy(elementSuccessPressed = color)
        "specialExtra01" -> copy(specialExtra01 = color)
        "specialExtra02" -> copy(specialExtra02 = color)
        "specialExtra03" -> copy(specialExtra03 = color)
        "specialExtra04" -> copy(specialExtra04 = color)
        "specialExtra05" -> copy(specialExtra05 = color)
        "specialExtra06" -> copy(specialExtra06 = color)
        "specialExtra07" -> copy(specialExtra07 = color)
        "specialExtra08" -> copy(specialExtra08 = color)
        "specialExtra09" -> copy(specialExtra09 = color)
        "specialExtra10" -> copy(specialExtra10 = color)
        "specialExtra11" -> copy(specialExtra11 = color)
        "specialExtra12" -> copy(specialExtra12 = color)
        "specialExtra13" -> copy(specialExtra13 = color)
        "specialExtra14" -> copy(specialExtra14 = color)
        "specialExtra15" -> copy(specialExtra15 = color)
        "specialExtra16" -> copy(specialExtra16 = color)
        "specialExtra17" -> copy(specialExtra17 = color)
        "specialExtra18" -> copy(specialExtra18 = color)
        "specialExtra19" -> copy(specialExtra19 = color)
        "specialExtra20" -> copy(specialExtra20 = color)
        "specialExtra21" -> copy(specialExtra21 = color)
        "specialExtra22" -> copy(specialExtra22 = color)
        "specialExtra23" -> copy(specialExtra23 = color)
        "specialExtra24" -> copy(specialExtra24 = color)
        "specialExtra25" -> copy(specialExtra25 = color)
        "specialExtra26" -> copy(specialExtra26 = color)
        "specialExtra27" -> copy(specialExtra27 = color)
        "textAccent" -> copy(textAccent = color)
        "textAccentAdditional" -> copy(textAccentAdditional = color)
        "textAccentPressed" -> copy(textAccentPressed = color)
        "textAdditional" -> copy(textAdditional = color)
        "textAttention" -> copy(textAttention = color)
        "textAttentionDefault" -> copy(textAttentionDefault = color)
        "textAttentionPressed" -> copy(textAttentionPressed = color)
        "textContrast" -> copy(textContrast = color)
        "textError" -> copy(textError = color)
        "textErrorDefault" -> copy(textErrorDefault = color)
        "textErrorPressed" -> copy(textErrorPressed = color)
        "textMask" -> copy(textMask = color)
        "textPrimary" -> copy(textPrimary = color)
        "textSecondary" -> copy(textSecondary = color)
        "textStaticWhite" -> copy(textStaticWhite = color)
        "textSuccess" -> copy(textSuccess = color)
        "textSuccessDefault" -> copy(textSuccessDefault = color)
        "textSuccessPressed" -> copy(textSuccessPressed = color)
        else -> this
    }
}

@Suppress("LongParameterList")
fun ColorPalette.copy(
    name: String = this.name,
    disabledAlpha: Double = this.disabledAlpha,
    backgroundAccent: Int = this.backgroundAccent,
    backgroundAccentDark: Int = this.backgroundAccentDark,
    backgroundAccentPressed: Int = this.backgroundAccentPressed,
    backgroundAdditionalOne: Int = this.backgroundAdditionalOne,
    backgroundAdditionalOnePressed: Int = this.backgroundAdditionalOnePressed,
    backgroundAdditionalTwo: Int = this.backgroundAdditionalTwo,
    backgroundAdditionalTwoPressed: Int = this.backgroundAdditionalTwoPressed,
    backgroundAttention: Int = this.backgroundAttention,
    backgroundAttentionPressed: Int = this.backgroundAttentionPressed,
    backgroundBasic: Int = this.backgroundBasic,
    backgroundError: Int = this.backgroundError,
    backgroundErrorPressed: Int = this.backgroundErrorPressed,
    backgroundExtraSurface: Int = this.backgroundExtraSurface,
    backgroundModalControl: Int = this.backgroundModalControl,
    backgroundModalView: Int = this.backgroundModalView,
    backgroundSecondary: Int = this.backgroundSecondary,
    backgroundSelected: Int = this.backgroundSelected,
    backgroundSelectedPressed: Int = this.backgroundSelectedPressed,
    backgroundShadow: Int = this.backgroundShadow,
    backgroundSuccess: Int = this.backgroundSuccess,
    backgroundSuccessPressed: Int = this.backgroundSuccessPressed,
    elementAccent: Int = this.elementAccent,
    elementAccentAdditional: Int = this.elementAccentAdditional,
    elementAccentPressed: Int = this.elementAccentPressed,
    elementAdditional: Int = this.elementAdditional,
    elementAttention: Int = this.elementAttention,
    elementAttentionDefault: Int = this.elementAttentionDefault,
    elementAttentionPressed: Int = this.elementAttentionPressed,
    elementBarDivider: Int = this.elementBarDivider,
    elementContrast: Int = this.elementContrast,
    elementError: Int = this.elementError,
    elementErrorDefault: Int = this.elementErrorDefault,
    elementErrorPressed: Int = this.elementErrorPressed,
    elementExtra: Int = this.elementExtra,
    elementPrimary: Int = this.elementPrimary,
    elementSecondary: Int = this.elementSecondary,
    elementStaticWhite: Int = this.elementStaticWhite,
    elementSuccess: Int = this.elementSuccess,
    elementSuccessDefault: Int = this.elementSuccessDefault,
    elementSuccessPressed: Int = this.elementSuccessPressed,
    specialExtra01: Int = this.specialExtra01,
    specialExtra02: Int = this.specialExtra02,
    specialExtra03: Int = this.specialExtra03,
    specialExtra04: Int = this.specialExtra04,
    specialExtra05: Int = this.specialExtra05,
    specialExtra06: Int = this.specialExtra06,
    specialExtra07: Int = this.specialExtra07,
    specialExtra08: Int = this.specialExtra08,
    specialExtra09: Int = this.specialExtra09,
    specialExtra10: Int = this.specialExtra10,
    specialExtra11: Int = this.specialExtra11,
    specialExtra12: Int = this.specialExtra12,
    specialExtra13: Int = this.specialExtra13,
    specialExtra14: Int = this.specialExtra14,
    specialExtra15: Int = this.specialExtra15,
    specialExtra16: Int = this.specialExtra16,
    specialExtra17: Int = this.specialExtra17,
    specialExtra18: Int = this.specialExtra18,
    specialExtra19: Int = this.specialExtra19,
    specialExtra20: Int = this.specialExtra20,
    specialExtra21: Int = this.specialExtra21,
    specialExtra22: Int = this.specialExtra22,
    specialExtra23: Int = this.specialExtra23,
    specialExtra24: Int = this.specialExtra24,
    specialExtra25: Int = this.specialExtra25,
    specialExtra26: Int = this.specialExtra26,
    specialExtra27: Int = this.specialExtra27,
    textAccent: Int = this.textAccent,
    textAccentAdditional: Int = this.textAccentAdditional,
    textAccentPressed: Int = this.textAccentPressed,
    textAdditional: Int = this.textAdditional,
    textAttention: Int = this.textAttention,
    textAttentionDefault: Int = this.textAttentionDefault,
    textAttentionPressed: Int = this.textAttentionPressed,
    textContrast: Int = this.textContrast,
    textError: Int = this.textError,
    textErrorDefault: Int = this.textErrorDefault,
    textErrorPressed: Int = this.textErrorPressed,
    textMask: Int = this.textMask,
    textPrimary: Int = this.textPrimary,
    textSecondary: Int = this.textSecondary,
    textStaticWhite: Int = this.textStaticWhite,
    textSuccess: Int = this.textSuccess,
    textSuccessDefault: Int = this.textSuccessDefault,
    textSuccessPressed: Int = this.textSuccessPressed,
): ColorPalette {
    return ColorPalette(
        name,
        disabledAlpha,
        backgroundAccent,
        backgroundAccentDark,
        backgroundAccentPressed,
        backgroundAdditionalOne,
        backgroundAdditionalOnePressed,
        backgroundAdditionalTwo,
        backgroundAdditionalTwoPressed,
        backgroundAttention,
        backgroundAttentionPressed,
        backgroundBasic,
        backgroundError,
        backgroundErrorPressed,
        backgroundExtraSurface,
        backgroundModalControl,
        backgroundModalView,
        backgroundSecondary,
        backgroundSelected,
        backgroundSelectedPressed,
        backgroundShadow,
        backgroundSuccess,
        backgroundSuccessPressed,
        elementAccent,
        elementAccentAdditional,
        elementAccentPressed,
        elementAdditional,
        elementAttention,
        elementAttentionDefault,
        elementAttentionPressed,
        elementBarDivider,
        elementContrast,
        elementError,
        elementErrorDefault,
        elementErrorPressed,
        elementExtra,
        elementPrimary,
        elementSecondary,
        elementStaticWhite,
        elementSuccess,
        elementSuccessDefault,
        elementSuccessPressed,
        specialExtra01,
        specialExtra02,
        specialExtra03,
        specialExtra04,
        specialExtra05,
        specialExtra06,
        specialExtra07,
        specialExtra08,
        specialExtra09,
        specialExtra10,
        specialExtra11,
        specialExtra12,
        specialExtra13,
        specialExtra14,
        specialExtra15,
        specialExtra16,
        specialExtra17,
        specialExtra18,
        specialExtra19,
        specialExtra20,
        specialExtra21,
        specialExtra22,
        specialExtra23,
        specialExtra24,
        specialExtra25,
        specialExtra26,
        specialExtra27,
        textAccent,
        textAccentAdditional,
        textAccentPressed,
        textAdditional,
        textAttention,
        textAttentionDefault,
        textAttentionPressed,
        textContrast,
        textError,
        textErrorDefault,
        textErrorPressed,
        textMask,
        textPrimary,
        textSecondary,
        textStaticWhite,
        textSuccess,
        textSuccessDefault,
        textSuccessPressed,
    )
}