name: Build Demo Release APK (Android)
on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened', 'edited']
    branches: ['main', 'develop', 'rc/**']
jobs:
  Build-Android-Demo-Release:
    runs-on: self-hosted
    env:
      ANDROID_SDK_ROOT: /Users/sbabakaev/Library/Android/sdk
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - name: Build Demo APK with Gradle
        run: ./gradlew assembleDebug --no-daemon